name: pipeline-orchestrator
networks:
  redpanda_network:
    driver: bridge
volumes:
  redpanda: null

services:
  redpanda:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.2.9
    container_name: redpanda
    volumes:
      - redpanda:/var/lib/redpanda/data
    networks:
      - redpanda_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v3.2.2
    networks:
      - redpanda_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda

  # --- BACKEND ---
  backend:
    build:
      context: ./backend/prototype
      dockerfile: manager/Dockerfile
    image: pipeline-orchestrator-backend:0.1.0
    container_name: pipeline_backend
    networks:
      - redpanda_network
    ports:
      - "8000:8000"
    volumes:
      # allows manager to spawn worker/producer containers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BROKER_ADDRESS=redpanda:9092
      - DOCKER_NETWORK_NAME=pipeline-orchestrator_redpanda_network
      - WORKER_IMAGE_NAME=pipeline-orchestrator-worker:0.1.0
      - PRODUCER_IMAGE_NAME=pipeline-orchestrator-producer:0.1.0
      - FASTAPI_EVENT_ENDPOINT=http://backend:8000/stream/event
    depends_on:
      - redpanda

  # ------------- FRONTEND -------------
  frontend:
    build:
      context: ./frontend/prototype
      dockerfile: Dockerfile
    image: pipeline-orchestrator-frontend:0.1.0
    container_name: pipeline_frontend
    ports:
      - "5173:5173"  
    depends_on:
      - backend
    networks:
      - redpanda_network
    volumes:
      - ./frontend/prototype:/app  
      - /app/node_modules          # prevent node_modules overwrite
  
  # ------------- WORKER IMAGE -------------
  worker:
    build:
      context: ./backend/prototype
      dockerfile: worker/Dockerfile
    image: pipeline-orchestrator-worker:0.1.0
    networks:
      - redpanda_network
    profiles: ["build-only"]
  
  # ------------- PRODUCER IMAGE -------------
  producer:
    build:
      context: ./backend/prototype
      dockerfile: producer/Dockerfile
    image: pipeline-orchestrator-producer:0.1.0
    networks:
      - redpanda_network
    profiles: ["build-only"]
